name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - name: Install Dependencies
      run: |
        brew update --preinstall
        brew install llvm ninja cmake lld
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        echo "/opt/homebrew/opt/make/libexec/gnubin" >> $GITHUB_PATH
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Make
      run: |
        cmake --preset debug
        cd build_debug && ninja
