name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - name: Install Dependencies
      run: |
        brew update --preinstall
        brew install llvm ninja cmake lld
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        echo "/opt/homebrew/opt/make/libexec/gnubin" >> $GITHUB_PATH
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Make directory
      run: |
        mkdir -p build_debug
    - name: Make
      working-directory: build_debug/
      run: |
        cmake .. -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_USING_LINKER_lld="-fuse-ld=lld" -DCMAKE_CXX_USING_LINKER_lld="-fuse-ld=lld" -DCMAKE_LINKER_TYPE=lld -DCMAKE_BUILD_TYPE=Debug
        ninja
